name: saker11
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.27+1
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.4.5
  responsive: ^0.2.3+4
  charts_flutter: ^0.9.0
  pie_chart: ^3.1.1
  dropdownfield: ^1.0.3
  dropdown_formfield: ^0.1.2
  sqflite: ^0.11.0
  path_provider: ^0.4.0
  http: ^0.12.0
  platform_alert_dialog: ^1.0.0+2
  local_auth: ^0.4.0+1






dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - homeimage/book.png
    - homeimage/fuclty.png
    - homeimage/control.png
    - homeimage/download.jpg
    - homeimage/logo.png
    - homeimage/logoo.png
    - homeimage/Group.png
    - homeimage/java.png
    - homeimage/mok.png
    - homeimage/built.png
    - homeimage/open.png
    - homeimage/ser.png
    - homeimage/map.png
    - homeimage/help.png
    - homeimage/lines.png
    - homeimage/c.jpg
    - homeimage/java.jpg
    - homeimage/python.jpg
    - homeimage/network.jpg
    - homeimage/library.png
    - homeimage/hello.png
    - homeimage/search.png
    - homeimage/Group4.png
    - homeimage/Group5.png
    - homeimage/Group6.png
    - homeimage/Group7.png
    - homeimage/Group8.png
    - homeimage/Group9.png
    - homeimage/Group10.png
    - homeimage/Iconawesome-chart-bar.png
    - homeimage/finger.png











  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-ExtraLight.ttf
        - asset: fonts/Cairo-Bold.ttf
  #          style: italic